In [1]:
# Dependencies
import numpy as np
import pandas as pd

In [2]:
# Read in csv
data = pd.read_csv('resources/data.csv')
data.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jul-13  2013   Jul                 139.5                    331.4   
1  Aug-13  2013   Aug                 146.7                    329.6   
2  Sep-13  2013   Sep                 139.7                    322.7   
3  Oct-13  2013   Oct                 127.9                    351.6   
4  Nov-13  2013   Nov                 138.5                    388.1   

   online_total_turnover  total_revenue_turnover  
0                  470.9                 22042.6  
1                  476.3                 22204.7  
2                  462.4                 22356.5  
3                  479.5                 22431.6  
4                  526.6                 22630.9

In [14]:
# Create new column for index so that regression can be done
data['index'] = range(1, len(data) + 1)
data.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jul-13  2013   Jul                 139.5                    331.4   
1  Aug-13  2013   Aug                 146.7                    329.6   
2  Sep-13  2013   Sep                 139.7                    322.7   
3  Oct-13  2013   Oct                 127.9                    351.6   
4  Nov-13  2013   Nov                 138.5                    388.1   

   online_total_turnover  total_revenue_turnover  index  
0                  470.9                 22042.6      1  
1                  476.3                 22204.7      2  
2                  462.4                 22356.5      3  
3                  479.5                 22431.6      4  
4                  526.6                 22630.9      5

In [4]:
# Create the model and fit the model to the data
from sklearn.linear_model import LinearRegression
model = LinearRegression()

### Get values for total online revenue

In [5]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = data.index.values.reshape(-1, 1)
y = data.online_total_turnover.values.reshape(-1, 1)

In [6]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[25.80915571]]
y-axis intercept:  [138.07363254]


In [7]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[91]]


In [8]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[93],[94],[95],[96]])
y_max_p

array([[2538.32511367],
       [2564.13426938],
       [2589.94342509],
       [2615.7525808 ]])

### Get values for total revenue

In [9]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = data.index.values.reshape(-1, 1)
y = data.total_revenue_turnover.values.reshape(-1, 1)

In [10]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[77.20694096]]
y-axis intercept:  [22404.73092567]


In [11]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[91]]


In [12]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[93],[94],[95],[96]])
y_max_p

array([[29584.97643451],
       [29662.18337546],
       [29739.39031642],
       [29816.59725737]])

### Get values for food online revenue

In [16]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = data.index.values.reshape(-1, 1)
y = data.online_food_turnover.values.reshape(-1, 1)

In [17]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[6.98838833]]
y-axis intercept:  [27.51963534]


In [18]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[91]]


In [19]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[93],[94],[95],[96]])
y_max_p

array([[677.43975001],
       [684.42813834],
       [691.41652667],
       [698.404915  ]])

### Get values for non-food online revenue

In [20]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = data.index.values.reshape(-1, 1)
y = data.online_nonfood_turnover.values.reshape(-1, 1)

In [21]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[18.82068184]]
y-axis intercept:  [110.55897616]


In [22]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[91]]


In [23]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[93],[94],[95],[96]])
y_max_p

array([[1860.88238753],
       [1879.70306937],
       [1898.52375121],
       [1917.34443306]])

### Add new values to data frame