In [1]:
# Dependencies
import numpy as np
import pandas as pd

In [2]:
# Read in csv
data = pd.read_csv('resources/data.csv')
data.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jul-2013  2013   Jul                 139.5                    331.4   
1  Aug-2013  2013   Aug                 146.7                    329.6   
2  Sep-2013  2013   Sep                 139.7                    322.7   
3  Oct-2013  2013   Oct                 127.9                    351.6   
4  Nov-2013  2013   Nov                 138.5                    388.1   

   online_total_turnover  total_revenue_turnover  
0                  470.9                 22042.6  
1                  476.3                 22204.7  
2                  462.4                 22356.5  
3                  479.5                 22431.6  
4                  526.6                 22630.9

In [3]:
# Read in csv
precovid = pd.read_csv('resources/covid.csv')
precovid.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jul-2013  2013   Jul                 139.5                    331.4   
1  Aug-2013  2013   Aug                 146.7                    329.6   
2  Sep-2013  2013   Sep                 139.7                    322.7   
3  Oct-2013  2013   Oct                 127.9                    351.6   
4  Nov-2013  2013   Nov                 138.5                    388.1   

   online_total_turnover  total_revenue_turnover  
0                  470.9                 22042.6  
1                  476.3                 22204.7  
2                  462.4                 22356.5  
3                  479.5                 22431.6  
4                  526.6                 22630.9

In [4]:
# Read in csv
postcovid = pd.read_csv('resources/predict.csv')
postcovid.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jan-2020  2020   Jan                 513.8                   1341.3   
1  Feb-2020  2020   Feb                 548.5                   1388.1   
2  Mar-2020  2020   Mar                 525.1                   1673.9   
3  Apr-2020  2020   Apr                 603.2                   2191.1   
4  May-2020  2020   May                 713.6                   2157.2   

   online_total_turnover  total_revenue_turnover  
0                 1855.0                 27608.3  
1                 1936.6                 27775.7  
2                 2199.0                 30033.3  
3                 2794.3                 24816.7  
4                 2870.7                 28940.1

In [5]:
# Create new column for index so that regression can be done
precovid['index'] = range(1, len(precovid) + 1)
precovid.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jul-2013  2013   Jul                 139.5                    331.4   
1  Aug-2013  2013   Aug                 146.7                    329.6   
2  Sep-2013  2013   Sep                 139.7                    322.7   
3  Oct-2013  2013   Oct                 127.9                    351.6   
4  Nov-2013  2013   Nov                 138.5                    388.1   

   online_total_turnover  total_revenue_turnover  index  
0                  470.9                 22042.6      1  
1                  476.3                 22204.7      2  
2                  462.4                 22356.5      3  
3                  479.5                 22431.6      4  
4                  526.6                 22630.9      5

In [6]:
# Create new column for index so that regression can be done
postcovid['index'] = range(1, len(postcovid) + 1)
postcovid.head()

date  year month  online_food_turnover  online_nonfood_turnover  \
0  Jan-2020  2020   Jan                 513.8                   1341.3   
1  Feb-2020  2020   Feb                 548.5                   1388.1   
2  Mar-2020  2020   Mar                 525.1                   1673.9   
3  Apr-2020  2020   Apr                 603.2                   2191.1   
4  May-2020  2020   May                 713.6                   2157.2   

   online_total_turnover  total_revenue_turnover  index  
0                 1855.0                 27608.3      1  
1                 1936.6                 27775.7      2  
2                 2199.0                 30033.3      3  
3                 2794.3                 24816.7      4  
4                 2870.7                 28940.1      5

In [7]:
# Create the model and fit the model to the data
from sklearn.linear_model import LinearRegression
model = LinearRegression()

## Get values for total online revenue

### Pre-covid data

In [8]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = precovid.index.values.reshape(-1, 1)
y = precovid.online_total_turnover.values.reshape(-1, 1)

In [9]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[18.23442633]]
y-axis intercept:  [349.74125284]


In [10]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[77]]


In [11]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max = model.predict(x_max)
print(f"Min y Value: {y_min}")
print(f"Max y Value: {y_max}")

Min y Value: [[349.74125284]]
Max y Value: [[1753.79208049]]


### Post-covid data

In [12]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = postcovid.index.values.reshape(-1, 1)
y = postcovid.online_total_turnover.values.reshape(-1, 1)

In [13]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[81.2221978]]
y-axis intercept:  [2236.49142857]


In [14]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[13]]


In [15]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max = model.predict(x_max)
print(f"Min y Value: {y_min}")
print(f"Max y Value: {y_max}")

Min y Value: [[2236.49142857]]
Max y Value: [[3292.38]]


In [16]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[15],[16],[17],[18]])
y_max_p

array([[3454.8243956 ],
       [3536.04659341],
       [3617.26879121],
       [3698.49098901]])

## Get values for total revenue

In [17]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = postcovid.index.values.reshape(-1, 1)
y = postcovid.total_revenue_turnover.values.reshape(-1, 1)

In [18]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[256.71450549]]
y-axis intercept:  [27669.53428571]


In [19]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[13]]


In [20]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[15],[16],[17],[18]])
y_max_p

array([[31520.25186813],
       [31776.96637363],
       [32033.68087912],
       [32290.39538462]])

## Get values for food online revenue

In [21]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = postcovid.index.values.reshape(-1, 1)
y = postcovid.online_food_turnover.values.reshape(-1, 1)

In [22]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[31.94153846]]
y-axis intercept:  [543.36571429]


In [23]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[13]]


In [24]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[15],[16],[17],[18]])
y_max_p

array([[1022.48879121],
       [1054.43032967],
       [1086.37186813],
       [1118.31340659]])

## Get values for non-food online revenue

In [25]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values
# so we use reshape to create this

X = postcovid.index.values.reshape(-1, 1)
y = postcovid.online_nonfood_turnover.values.reshape(-1, 1)

In [26]:
# Fit the model to the data. 
# Note: This is the training step where you fit the line to the data.
model.fit(X, y)

# Print the coefficient and the intercept for the model
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [[49.27736264]]
y-axis intercept:  [1693.15428571]


In [27]:
# Note: we have to transform our min and max values 
# so they are in the format: array([[ 1.17]])
# This is the required format for `model.predict()`
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[0]]
Max X Value: [[13]]


In [28]:
# Calculate the y_min and y_max using model.predict and x_min and x_max
y_min = model.predict(x_min)
y_max_p = model.predict( [[15],[16],[17],[18]])
y_max_p

array([[2432.31472527],
       [2481.59208791],
       [2530.86945055],
       [2580.14681319]])

## Add new values to data frame

In [29]:
# New rows:
march_2021 = {'date':'Mar-2021', 'year':2021, 'month':'Mar', 'online_food_turnover':1022.48879121, 'online_nonfood_turnover':2432.31472527, 'online_total_turnover':3454.8243956, 'total_revenue_turnover':31520.25186813}

april_2021 = {'date':'Apr-2021', 'year':2021, 'month':'Apr', 'online_food_turnover':1054.43032967, 'online_nonfood_turnover':2481.59208791, 'online_total_turnover':3536.04659341, 'total_revenue_turnover':31776.96637363}

may_2021 = {'date':'May-2021', 'year':2021, 'month':'May', 'online_food_turnover':1086.37186813, 'online_nonfood_turnover':2530.86945055, 'online_total_turnover':3617.26879121, 'total_revenue_turnover':32033.68087912}

june_2021 = {'date':'Jun-2021', 'year':2021, 'month':'Jun', 'online_food_turnover':1118.31340659, 'online_nonfood_turnover':2580.14681319, 'online_total_turnover':3698.49098901, 'total_revenue_turnover':32290.39538462}

In [31]:
#append row to the dataframe
data = data.append(march_2021, ignore_index=True)
data.tail()

date  year month  online_food_turnover  online_nonfood_turnover  \
88  Nov-2020  2020   Nov            813.100000              2223.300000   
89  Dec-2020  2020   Dec            864.100000              2107.200000   
90  Jan-2021  2021   Jan            903.900000              2117.100000   
91  Feb-2021  2021   Feb            892.800000              2060.600000   
92  Mar-2021  2021   Mar           1022.488791              2432.314725   

    online_total_turnover  total_revenue_turnover  
88            3036.400000            31571.400000  
89            2971.300000            30450.900000  
90            3021.000000            30538.500000  
91            2953.400000            30300.600000  
92            3454.824396            31520.251868

In [32]:
#append row to the dataframe
data = data.append(april_2021, ignore_index=True)
data = data.append(may_2021, ignore_index=True)
data = data.append(june_2021, ignore_index=True)
data.tail()

date  year month  online_food_turnover  online_nonfood_turnover  \
91  Feb-2021  2021   Feb            892.800000              2060.600000   
92  Mar-2021  2021   Mar           1022.488791              2432.314725   
93  Apr-2021  2021   Apr           1054.430330              2481.592088   
94  May-2021  2021   May           1086.371868              2530.869451   
95  Jun-2021  2021   Jun           1118.313407              2580.146813   

    online_total_turnover  total_revenue_turnover  
91            2953.400000            30300.600000  
92            3454.824396            31520.251868  
93            3536.046593            31776.966374  
94            3617.268791            32033.680879  
95            3698.490989            32290.395385

## Save dataframe as csv and go to ETL load to put into postgres


In [33]:
data.to_csv('resources/final.csv',index = False, header=True)